#
# (C) Copyright 2016 Nexell
# Hyunseok, Jung <hsjung@nexell.co.kr>
#
# SPDX-License-Identifier:      GPL-2.0+
#

obj-y				+= clock.o
obj-y				+= timer.o
obj-y				+= reset.o
obj-y				+= nx_gpio.o
obj-y				+= tieoff.o
obj-$(CONFIG_S5P_SERIAL) 	+= serial.o
